Smooth random voltages script
Allen-Synthesis/EuroPi pull request #153
Opened 2022-06-02 01:29 UTC by awonak

3 smooth unique random voltages paired with matching stepped random voltages.

2022-06-04 17:33 UTC, awonak commented
I've got a few issues I'd like to fix before we merge.
1. slew on short voltage hops is not very smooth (need to increase granularity of slew)
2. analog input is not outputting 1:1 (pitch cv does not retain accurate cv value on output)

2022-06-08 15:03 UTC, mjaskula reviewed
Looks good to me so far.  I'll hold off on approval since you said you are not finished yet.

2022-07-24 15:02 UTC, awonak commented on software/contrib/smooth_random_voltages.py
> +machine.freq(250000000)
Done. I ended up removing it as it wasn't really necessary here.

2022-07-26 23:39 UTC, mjaskula requested changes
Looks pretty good to me. I've opened up some discussion on a couple ways to improve the EnvelopeGenerator class, as well as a documentation change. Let me know what you think.

2022-08-01 13:41 UTC, awonak commented on software/contrib/smooth_random_voltages.py
> +class EnvelopeGenerator:
Both good calls, I went with the generator function instead of the class wrapper.

2022-08-01 14:02 UTC, awonak commented on software/contrib/smooth_random_voltages.py
> +labels: random, s&h
Done.

> This should especially help people who are new to synthesis and might not make the connection.

While this is helpful, I don't think we should make this a requirement for script authors.

2022-08-02 21:14 UTC, mjaskula approved these changes
Thanks for making these changes. The code looks good to me now. I haven't had a chance yet to fire it up and try it and see the UI, but I don't think that is required for merge. Especially since @roryjamesallen has run it. In general, it's probably a good idea if we verify that a script runs on a couple EuroPis before merge.

2022-08-03 22:42 UTC, awonak commented on software/contrib/smooth_random_voltages.py
> +        self.slew_rate = lambda: europi.k1.range(50000)
I doubled the max slew rate and added a constant to make it easier to adjust in the script.

The tricky thing with the exponential slew is that if the max slew rate is too high, then lower knob settings become much trickier to dial in versus the larger values. I originally had a linear slew which didn't have this problem, but I liked the effect of the exponential curve better, so it's a trade-off.

2022-08-07 17:36 UTC, awonak commented
I finally got a chance to test this script on my module one more time. Worked as expected, I'm gonna merge now.

2022-08-07 17:37 UTC, merged