Add additional documentation for the use of custom images on the oled.
Allen-Synthesis/EuroPi pull request #195
Opened 2022-11-14 06:26 UTC by redoxcode

This PR adds additional documentation for the use of custom images on the oled display and also addresses potential screen burn in as mentioned here: https://github.com/Allen-Synthesis/EuroPi/issues/83

2022-11-15 17:23 UTC, mjaskula requested changes
Hello, thanks for your PR. It's always great to have some documentation updates. If you haven't yet, pleas read the [contributing guide](https://github.com/Allen-Synthesis/EuroPi/blob/main/contributing.md) so that you know what to expect during your PR.

This one looks pretty good to me. I highlighted a couple typos to be corrected, and opened a discussion on the image used in the example. Once we have these resolved we can get this merged. Thanks again for your contribution. I hope that there will be more.

2022-11-15 17:23 UTC, mjaskula commented on software/oled_tips.md
> +Make sure your jpg has the right size and you use the same size when you run this tool und in the micropython code.
[required] 'und' -> 'and'

2022-11-15 17:23 UTC, mjaskula commented on software/oled_tips.md
> +If you write a script consider adding a 'screensaver' function (for example clear the screen if there was no user interaction for an extended time periode).
[required] typo 'periode'

2022-11-15 19:01 UTC, mjaskula commented on software/oled_tips.md
> +img=b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\x80\x00\x00~\x00\x00\x00<\x00\x00\x00<\x00\x00\x00<\x00\x00\x00>\x00\x00\x00>\x00\x00>>\x00\x00>>\x00\x00>?\x80\x00\x1d\xff\xff\xc0?\xff
🤦 Yeah, that's it. I just swapped in the bitmap. Sorry. Changing the size reveals a spaceship. I do think the leaf is 'better' though, so thanks for the change.

2022-11-15 19:02 UTC, mjaskula approved these changes
Looks good to me now. Thanks!

2022-11-15 19:04 UTC, merged

2022-11-19 19:50 UTC, roryjamesallen commented
LGTM, thanks for adding to the docs!