2 Point calibration fix
Allen-Synthesis/EuroPi pull request #232
Opened 2023-02-28 07:51 UTC by redoxcode

This PR should fix an oversight in the way the calibration values are applied when using only 2 Points.
The issue was described here: https://github.com/Allen-Synthesis/EuroPi/issues/221#issuecomment-1446950213
In short: If we are not mistaken the adc offset measured when 0V is applied, is currently not taken into account.
Old:
result = 'adc raw value' / 'calibration at 10V'
New:
result = ('adc raw value' - 'calibration at 0V') / ('calibration at 10V' - 'calibration at 0V)

(some tests still fail, but it's only one contrib script (tests/contrib/test_europi_turing_machine.py) so I guess it's an issue of this test and not the code changes)

2023-03-15 19:21 UTC, awonak commented
@redoxcode do you have some time to sync this branch to HEAD, and fix the lint and test errors? We'd love to include this in our next release.

2023-03-16 08:21 UTC, redoxcode commented
@awonak sync is done. I will try to work out why tests fail

2023-03-16 13:55 UTC, redoxcode commented
ok, there where some bugs in the implementation and some corner cases I missed (like when the input is below the 0 point calibration). But I think its good now!
But please check on actual hardware and do the calibration.
I also had to fix the 2 point calibration in the mock hardware.
And some how my black output was different than what lint wants :thinking:

2023-03-17 12:30 UTC, roryjamesallen requested changes

2023-03-17 12:30 UTC, roryjamesallen commented on software/firmware/europi.py
> +        return max((reading - INPUT_CALIBRATION_VALUES[0]) / max_value, 0.0)
the calculation of ```reading - INPUT_CALIBRATION_VALUES[0]``` is made twice, I'd suggest making the calculation between lines 215 and 216 with something like
```offset = reading - INPUT_CALIBRATION_VALUES[0]``` and then refer to that offset

2023-03-17 12:30 UTC, roryjamesallen commented on software/firmware/europi.py
> +        percent = max((reading - INPUT_CALIBRATION_VALUES[0]) / max_value, 0.0)
The same duplicated code comment as above

2023-03-19 17:22 UTC, awonak commented
LGTM, thank you for improving the calibration process @redoxcode & @francoisgeorgy

2023-03-19 17:22 UTC, merged