Add Beat Writer script
Allen-Synthesis/EuroPi pull request #263
Opened 2023-04-25 15:55 UTC by roryjamesallen

A script that lets you program 2 channels of drum patterns and add randomisation

2023-05-04 02:19 UTC, mjaskula requested changes
Overall this looks pretty good to me, code wise, though i did't try it out yet in hardware. I added some optional and required code improvements. Let me know what you think.

2023-05-04 02:19 UTC, mjaskula commented on software/contrib/beat_writer.py
> +        self.din_out = cv1
[optional] For consistency with the fields below:

```suggestion
        self.din_output = cv1
```

2023-05-04 02:19 UTC, mjaskula commented on software/contrib/beat_writer.py
> +    def reset_rhythm(self, rhythm):
[required] This function effectively duplicates the functionality of `create_blank_rhythm`.  I think that we only need one of them. If you got rid of this function, then the code in `check_if_reset_rhythm_2` could use:

```python
if b2_difference > 300:
    self.rhythm_2 = create_blank_rhythm(self.length)
```

2023-05-04 02:19 UTC, mjaskula commented on software/contrib/beat_writer.py
> +            rhythm[(self.step - 1) % self.length] = 1 - rhythm[(self.step + 1) % self.length]	#Invert the current step
```suggestion
            rhythm[(self.step - 1) % self.length] = 1 - rhythm[(self.step + 1) % self.length]	#Invert the previous step
```

2023-05-04 02:19 UTC, mjaskula commented on software/contrib/beat_writer.py
> +        oled.centre_text('BEAT WRITER\n\nplug in clock')
[optional] Maybe specify where to plug in a clock?

2023-05-04 19:55 UTC, mjaskula commented on software/contrib/beat_writer.py
> +        output_2_value = randint(0, 1) if randint(2, 98) < self.randomisation_2 else self.rhythm_2[self.step]
That's fine, I just wanted to make sure that it was intentional. In this case I think that the documentation should be updated to describe this more accurately. As it is now, it reads to me as if it's the probability of a beat.

2024-01-30 15:02 UTC, roryjamesallen commented
Outdated

2024-01-30 15:02 UTC, closed without merging