Add Organisms script
Allen-Synthesis/EuroPi pull request #295
Opened 2023-08-10 14:09 UTC by roryjamesallen

This script births 6 organisms on start-up.

- Each organism has a 'boredom' attribute expressed as a percentage between 0 and 100
- Each organism has a 'speed' attribute expressed as a number between 1 and 10
- When moving, each organism has a 'destination' expressed as a set of coordinates

Upon each tick of the script's clock:
- Each organism's boredom will increase by 1 if they aren't moving, or decrease by 2 if they are
- Each organism will calculate, using boredom and a random integer, whether it should begin walking
- If an organism is to begin walking, it will pick a new destination on the screen
- If an organism is already walking, it will move towards its destination at its own speed
- If an organism reaches its destination (or would exceed it in the next tick) it stops walking
- If two organisms come within `fight_radius` of each other, they will "fight" - a white rectangle around the OLED indicates that a fight is taking place
- When two organisms fight, there is a 50% chance that either will win
- The winner's speed increases by 1, and the loser's decreases by 1

2023-10-02 22:33 UTC, mjaskula requested changes
Hey @roryjamesallen, this looks like a pretty fun little script. I left some comments on where I think that it could improve as well as some questions on things that I didn't understand. There's only a few things that I think _need_ to change before merge. Let me know what you think.

2023-10-08 14:54 UTC, roryjamesallen commented on software/contrib/organisms.md
> +- All energy must be maintained, so an organism with a speed of 1 cannot lose a fight, as it has nothing left to lose, and an organism with a speed of 6 cannot win a fight, as it has reached the spee
Exactly, this helps the system never go all fast or all slow, so at least one LFO will have a fair amount of energy. If it helps I can add this to the docs in a way that fits into the 'idea' of the script:  
  
"If an organism has an energy of 1, other organisms will take pity on it and allow it to win or draw all fights with it. If an organism has an energy of 6, they are satisfied with themselves and selflessly refuse the prize of energy transfer if they win a fight, so will only draw or lose to other organisms"

2023-10-08 14:56 UTC, roryjamesallen commented on software/contrib/organisms.md
> +    digital in: frantic mode (gate)
Good idea, I'll add a description!

2023-10-08 14:56 UTC, roryjamesallen commented on software/contrib/organisms.py
> +        self.maximum_speed = 6
You're right, it's left over as a variable per Organism because of how it was originally implemented but it should be global

2024-02-05 21:48 UTC, roryjamesallen commented
Outdated, may be reopened in future

2024-02-05 21:48 UTC, closed without merging