Add I²C Parameters to Config
Allen-Synthesis/EuroPi pull request #340
Opened 2024-02-13 19:38 UTC by roryjamesallen

- Add I²C SDA, SCL, and Channel to config options
- Use these parameters in `europi.py` for the Display initialisation
- Use SDA and SCL as default values in Display initialisation, allowing for initialisation with zero parameters i.e. `oled = Display()`
Other parameters already used default values set as global variables, so SDA and SCL seemed to have been missed as an oversight rather than deliberate choice.

This sets up the config settings for the future, preparing it for the implementation of suggestions like buttons to set multiple config settings based on model in an interactive config editor

2024-02-13 20:56 UTC, mjaskula approved these changes
I don't really understand the available sda and scl choices, so I'm just trusting you there. Otherwise this looks good to me.

2024-02-13 21:03 UTC, roryjamesallen commented
> I don't really understand the available sda and scl choices, so I'm just trusting you there. Otherwise this looks good to me.

These are all the SDA and SCL pins on the Pico/RP2040 - only these specific pins can be set as SDA/SCL so it helps prevent the setting of pins which couldn't possibly work, so the only room for error is just connecting the hardware to the wrong ones in a DIY build

2024-02-14 03:26 UTC, chrisib requested changes
Don't forget to update `CONFIGURATION.md` with these changes, please

2024-02-14 13:48 UTC, roryjamesallen commented
> Don't forget to update `CONFIGURATION.md` with these changes, please

Done

2024-02-15 07:35 UTC, merged