Consequencer, circuit.js model, calibrate.py print statements.
Allen-Synthesis/EuroPi pull request #75
Opened 2022-02-11 13:23 UTC by gamecat69

Added Consequencer. Added circuit.js output stages model. Added print statements to callibrate.py to help troubleshoot when it hangs if it cannot reach 10V.

2022-02-11 20:17 UTC, awonak reviewed
Nice script! The code is clean, well documented and easy to read. This is an excellent addition to the contrib folder.

A few requests before approving the script:
- Remove the `.DS_Store` file
- Move the falstad circuity file to its own folder
- Delete any commented out lines that are no longer used
- Consolidate the patterns with the consequencer.py script
- Remove print statements from calibrate.py

2022-02-11 20:17 UTC, awonak commented on software/contrib/consequencer.py
> +        k1Val = k1.read_position()
Consider simplifying this method by leveraging [Knob.choice()](https://allen-synthesis.github.io/EuroPi/generated/europi.html#europi.Knob.choice) or remove it (it looks like its references are commented out).
```suggestion
    return k1.choice([1, 2, 3, 4, 5, 6, 7, 8, 16, 32])
```

2022-02-11 20:17 UTC, awonak commented on software/contrib/consequencer_patterns.py
> +class pattern:
With the official repo contrib folder, we are trying to keep scripts contained to a single file so it's easy for all users to simply copy a single script to `main.py`. Can you move the pattern class into your main script, so it fully self contained in a single file? I will update the contrib README to make this more clear in the future.

2022-02-11 20:17 UTC, awonak commented on software/firmware/calibrate.py
> +    print(str(index+1) + 'V duty: ' + str(duty))
The calibrate script is intended to be headless, so we'd like to keep the print statements out. Was there a problem this was trying to solve? If so, lets fix that problem or open up a ticket to tackle later.

2022-02-12 13:40 UTC, roryjamesallen commented on hardware/schematic/cv-output-opamp.circuitjs.txt
> +$ 1 0.000005 10.20027730826997 57 5 50 5e-11
I think just 'falstad' is good! People are already in the schematics folder so that part should be obvious

2022-02-12 16:02 UTC, mjaskula requested changes
This looks great. I agree with @awonak on the changes he requested, and added a few other minor changes. I'm looking forward to giving this a try.

2022-02-12 21:58 UTC, closed without merging