Adding OLED Stand
Allen-Synthesis/EuroPi pull request #86
Opened 2022-02-21 20:37 UTC by aTanguay

The resources for printing your own OLED stand

2022-02-22 04:05 UTC, mjaskula approved these changes
I can't evaluate the blend or STL file, but he text and file organization look good to me.

2022-02-22 04:05 UTC, mjaskula commented on hardware/OLED_Stand/readme.md
> +Print upside down for best results/least amount of supports. Should print very quickly on most printers. It takes 30 minutes on my Ender3 Pro.
Nitpick: use 3rd person, as in:

> It takes 30 minutes on an Ender3 Pro.

2022-02-22 12:45 UTC, roryjamesallen commented
It doesn't really matter given very few people will be using the .blend file to *modify* the designs, however it seems like there is an extra unused boolean cutter 'Cube.005'. Minor change but might be worth getting rid of just to reduce confusion for anyone trying to modify the designs.
It could also be worth renaming the other cutters to something like 'Boolean_Cutter_1' etc, or any other naming format that just gives them a bit of context *or* if this is a fixed design not made to be modified, just apply the boolean modifiers and only have the single Master object

2022-02-22 12:47 UTC, roryjamesallen requested changes
It doesn't really matter given very few people will be using the .blend file to modify the designs, however it seems like there is an extra unused boolean cutter 'Cube.005'. Minor change but might be worth getting rid of just to reduce confusion for anyone trying to modify the designs.
It could also be worth renaming the other cutters to something like 'Boolean_Cutter_1' etc, or any other naming format that just gives them a bit of context or if this is a fixed design not made to be modified, just apply the boolean modifiers and only have the single Master object

2022-02-24 02:00 UTC, aTanguay commented on hardware/OLED_Stand/readme.md
> +Print upside down for best results/least amount of supports. Should print very quickly on most printers. It takes 30 minutes on my Ender3 Pro.
🙄

2022-02-24 02:06 UTC, closed without merging